const fs = require('fs');

// Build complete sections array from the comprehensive TOC with physical PDF pages
const sections = [];

// Helper to add section
const addSection = (sectionNumber, sectionTitle, tocPage) => {
  sections.push({
    sectionNumber: String(sectionNumber),
    sectionTitle: sectionTitle,
    page: tocPage + 26 // Convert TOC page to physical PDF page
  });
};

// Helper to add part/division/subdivision headers (no page)
const addHeader = (sectionNumber, sectionTitle) => {
  sections.push({
    sectionNumber: String(sectionNumber),
    sectionTitle: sectionTitle
  });
};

// Part 1 - Preliminary
addHeader("Part 1", "Preliminary");
addHeader("Division 1", "Introduction");
addSection("1", "Short title", 2);
addSection("2", "Commencement", 2);
addHeader("Division 2", "Object");
addSection("3", "Object", 2);
addHeader("Division 3", "Interpretation");
addHeader("Subdivision 1", "Definitions");
addSection("4", "Definitions", 4);
addHeader("Subdivision 2", "Other important terms");
addSection("4A", "Meaning of officer", 10);
addSection("5", "Meaning of person conducting a business or undertaking", 12);
addSection("6", "Meaning of supply", 13);
addSection("7", "Meaning of worker", 14);
addSection("8", "Meaning of workplace", 14);
addSection("9", "Notes", 15);
addHeader("Division 4", "Application of Act");
addSection("10", "Act binds Crown", 15);
addSection("11", "Not used", 15);
addSection("12", "Not used", 15);
addHeader("Division 5", "Establishment of various offices and bodies");
addSection("12A", "Effect of Schedule 1", 15);

// Part 2 - Health and safety duties
addHeader("Part 2", "Health and safety duties");
addHeader("Division 1", "Introductory");
addHeader("Subdivision 1", "Principles that apply to duties");
addSection("13", "Principles that apply to duties", 16);
addSection("14", "Duties not transferable", 16);
addSection("15", "Person may have more than 1 duty", 16);
addSection("16", "More than 1 person can have a duty", 16);
addSection("17", "Management of risks", 17);
addHeader("Subdivision 2", "What is reasonably practicable");
addSection("18", "What is reasonably practicable in ensuring health and safety", 17);
addHeader("Division 2", "Primary duty of care");
addSection("19", "Primary duty of care", 18);
addHeader("Division 3", "Further duties of persons conducting businesses or undertakings");
addSection("20", "Duty of persons conducting businesses or undertakings involving management or control of workplaces", 20);
addSection("21", "Duty of persons conducting businesses or undertakings involving management or control of fixtures, fittings or plant at workplaces", 20);
addSection("22", "Duties of persons conducting businesses or undertakings that design plant, substances or structures", 21);
addSection("23", "Duties of persons conducting businesses or undertakings that manufacture plant, substances or structures", 23);
addSection("24", "Duties of persons conducting businesses or undertakings that import plant, substances or structures", 25);
addSection("25", "Duties of persons conducting businesses or undertakings that supply plant, substances or structures", 27);
addSection("26", "Duty of persons conducting businesses or undertakings that install, construct or commission plant or structures", 29);
addSection("26A", "Duty of persons conducting businesses or undertakings that provide services relating to work health and safety", 30);
addHeader("Division 4", "Duty of officers, workers and other persons");
addSection("27", "Duty of officers", 32);
addSection("28", "Duties of workers", 33);
addSection("29", "Duties of other persons at the workplace", 34);
addHeader("Division 5", "Offences and penalties");
addHeader("Subdivision 1", "Preliminary");
addSection("30", "Terms used", 34);
addHeader("Subdivision 2", "Industrial manslaughter");
addSection("30A", "Industrial manslaughter — crime", 35);
addHeader("Subdivision 3", "Other offences and penalties");
addSection("31", "Failure to comply with health and safety duty — Category 1", 36);
addSection("32", "Failure to comply with health and safety duty — Category 2", 38);
addSection("33", "Failure to comply with health and safety duty — Category 3", 38);
addHeader("Subdivision 4", "Exceptions");
addSection("34", "Volunteers and unincorporated associations", 39);

// Part 3 - Incident notification
addHeader("Part 3", "Incident notification");
addSection("35", "What is a notifiable incident", 40);
addSection("36", "What is a serious injury or illness", 40);
addSection("37", "What is a dangerous incident", 41);
addSection("38", "Duty to notify of notifiable incidents", 42);
addSection("39", "Duty to preserve incident sites", 43);

// Part 4 - Authorisations
addHeader("Part 4", "Authorisations");
addHeader("Division 1", "Preliminary");
addSection("40", "Meaning of authorised", 45);
addHeader("Division 2", "Requirements for authorisations");
addSection("41", "Requirements for authorisation of workplaces", 45);
addSection("42", "Requirements for authorisation of plant or substance", 45);
addSection("43", "Requirements for authorisation of work", 46);
addHeader("Division 3", "Other requirements");
addSection("44", "Requirements for prescribed qualifications or experience", 47);
addSection("45", "Requirement to comply with conditions of authorisation", 48);
addHeader("Division 4", "Use of automated electronic systems for functions relating to authorisations");
addSection("45A", "Preliminary", 48);
addSection("45B", "Use of automated electronic systems under authorisation provisions", 49);
addSection("45C", "Replacing decision made by automated electronic system or re-exercising or re-performing authorisation function", 50);

// Part 5 - Consultation, representation and participation
addHeader("Part 5", "Consultation, representation and participation");
addHeader("Division 1", "Consultation, cooperation and coordination between duty holders");
addSection("46", "Duty to consult with other duty holders", 52);
addHeader("Division 2", "Consultation with workers");
addSection("47", "Duty to consult workers", 52);
addSection("48", "Nature of consultation", 53);
addSection("49", "When consultation is required", 53);
addHeader("Division 3", "Health and safety representatives");
addHeader("Subdivision 1", "Request for election of health and safety representatives");
addSection("50", "Request for election of health and safety representative", 54);
addHeader("Subdivision 2", "Determination of work groups");
addSection("51", "Determination of work groups", 54);
addSection("52", "Negotiations for determination of work group", 55);
addSection("53", "Notice to workers", 56);
addSection("54", "Failure of negotiations", 56);
addHeader("Subdivision 3", "Multiple business work groups");
addSection("55", "Determination of work groups of multiple businesses", 57);
addSection("56", "Negotiation of agreement for work groups of multiple businesses", 58);
addSection("57", "Notice to workers", 59);
addSection("58", "Withdrawal from negotiations or agreement involving multiple businesses", 60);
addSection("59", "Effect of Subdivision on other arrangements", 60);
addHeader("Subdivision 4", "Election of health and safety representatives");
addSection("60", "Eligibility to be elected", 60);
addSection("61", "Procedure for election of health and safety representatives", 61);
addSection("62", "Eligibility to vote", 61);
addSection("63", "When election not required", 61);
addSection("64", "Term of office of health and safety representative", 62);
addSection("65", "Disqualification of health and safety representatives", 62);
addSection("66", "Immunity of health and safety representatives", 63);
addSection("67", "Deputy health and safety representatives", 63);
addHeader("Subdivision 5", "Powers and functions of health and safety representatives");
addSection("68", "Powers and functions of health and safety representatives", 64);
addSection("69", "Powers and functions generally limited to the particular work group", 67);
addHeader("Subdivision 6", "Obligations of person conducting business or undertaking to health and safety representatives");
addSection("70", "General obligations of person conducting business or undertaking", 68);
addSection("71", "Exceptions from obligations under section 70(1)", 70);
addSection("72", "Obligation to train health and safety representatives", 71);
addSection("73", "Obligation to share costs if multiple businesses or undertakings", 73);
addSection("74", "List of health and safety representatives", 73);
addHeader("Division 4", "Health and safety committees");
addSection("75", "Health and safety committees", 74);
addSection("76", "Constitution of committee", 75);
addSection("77", "Functions of committee", 76);
addSection("78", "Meetings of committee", 76);
addSection("79", "Duties of person conducting business or undertaking", 76);
addHeader("Division 5", "Issue resolution");
addSection("80", "Parties to an issue", 78);
addSection("81", "Resolution of health and safety issues", 79);
addSection("82", "Referral of issue to regulator for resolution by inspector", 79);
addSection("82A", "Extension of deadline for making decision resolving issue", 80);
addHeader("Division 6", "Right to cease or direct cessation of unsafe work");
addSection("83", "Definition of cease work under this Division", 80);
addSection("84", "Right of worker to cease unsafe work", 81);
addSection("85", "Health and safety representative may direct that unsafe work cease", 81);
addSection("86", "Worker to notify if ceases work", 82);
addSection("87", "Alternative work", 83);
addSection("88", "Continuity of engagement of worker", 83);
addSection("89", "Request to regulator to appoint inspector to assist", 83);
addSection("89A", "Referral of issue about application of section 88 to Tribunal", 83);
addHeader("Division 7", "Provisional improvement notices");
addSection("90", "Provisional improvement notices", 84);
addSection("91", "Provisional improvement notice to be in writing", 85);
addSection("92", "Contents of provisional improvement notice", 85);
addSection("93", "Provisional improvement notice may include recommendations to remedy contravention", 85);
addSection("94", "Minor changes to provisional improvement notice", 86);
addSection("95", "Issue of provisional improvement notice", 86);
addSection("96", "Health and safety representative may cancel notice", 86);
addSection("97", "Display of provisional improvement notice", 86);
addSection("98", "Formal irregularities or defects in notice", 87);
addSection("99", "Offence to contravene a provisional improvement notice", 87);
addSection("100", "Request for review of provisional improvement notice", 87);
addSection("101", "Inspector to review notice", 88);
addSection("102", "Decision of inspector on review of provisional improvement notice", 88);
addHeader("Division 8", "Part not to apply to prisoners");
addSection("103", "Part does not apply to prisoners", 89);

// Part 6 - Discriminatory, coercive and misleading conduct
addHeader("Part 6", "Discriminatory, coercive and misleading conduct");
addHeader("Division 1", "Prohibition on discriminatory, coercive or misleading conduct");
addSection("104", "Prohibition on discriminatory conduct", 90);
addSection("105", "What is discriminatory conduct", 90);
addSection("106", "What is a prohibited reason", 91);
addSection("107", "Prohibition of requesting, instructing, inducing, encouraging, authorising or assisting discriminatory conduct", 93);
addSection("108", "Prohibition of coercion or inducement", 93);
addSection("109", "Misrepresentation", 94);
addHeader("Division 2", "Criminal proceedings in relation to discriminatory conduct");
addSection("110", "Proof of discriminatory conduct", 95);
addSection("111", "Order for compensation or reinstatement", 95);
addHeader("Division 3", "Civil proceedings in relation to discriminatory or coercive conduct");
addSection("112", "Civil proceedings in relation to engaging in or inducing discriminatory or coercive conduct", 96);
addSection("113", "Procedure for civil actions for discriminatory conduct", 97);
addHeader("Division 4", "General");
addSection("114", "General provisions relating to orders", 98);
addSection("115", "Prohibition on multiple actions", 99);

// Part 7 - Not used
addHeader("Part 7", "Not used");
addHeader("Division 1", "Not used");
addSection("116", "Not used", 100);
addHeader("Division 2", "Not used");
addSection("117", "Not used", 100);
addSection("118", "Not used", 100);
addSection("119", "Not used", 100);
addHeader("Division 3", "Not used");
addSection("120", "Not used", 100);
addSection("121", "Not used", 100);
addSection("122", "Not used", 100);
addHeader("Division 4", "Not used");
addSection("123", "Not used", 100);
addSection("124", "Not used", 100);
addSection("125", "Not used", 100);
addSection("126", "Not used", 100);
addSection("127", "Not used", 100);
addSection("128", "Not used", 100);
addSection("129", "Not used", 100);
addSection("130", "Not used", 100);
addHeader("Division 5", "Not used");
addSection("131", "Not used", 101);
addSection("132", "Not used", 101);
addSection("133", "Not used", 101);
addSection("134", "Not used", 101);
addSection("135", "Not used", 101);
addSection("136", "Not used", 101);
addSection("137", "Not used", 101);
addSection("138", "Not used", 101);
addSection("139", "Not used", 101);
addSection("140", "Not used", 101);
addHeader("Division 6", "Not used");
addSection("141", "Not used", 101);
addSection("142", "Not used", 101);
addSection("143", "Not used", 101);
addHeader("Division 7", "Not used");
addSection("144", "Not used", 101);
addSection("145", "Not used", 101);
addSection("146", "Not used", 101);
addSection("147", "Not used", 101);
addSection("148", "Not used", 102);
addHeader("Division 8", "Not used");
addSection("149", "Not used", 102);
addSection("150", "Not used", 102);
addSection("151", "Not used", 102);

// Part 8 - The regulator
addHeader("Part 8", "The regulator");
addHeader("Division 1", "Functions of regulator");
addSection("152", "Functions of regulator", 103);
addSection("153", "Powers of regulator", 104);
addSection("154", "Delegation by regulator", 104);
addHeader("Division 2", "Powers of regulator to obtain information and require independent reports");
addSection("155", "Powers of regulator to obtain information", 104);
addSection("155A", "Supplementary provisions relating to appearances", 106);
addSection("155B", "Power of regulator to require independent report", 107);
addSection("155C", "Powers to copy and retain documents", 108);

// Part 9 - Securing compliance
addHeader("Part 9", "Securing compliance");
addHeader("Division 1", "Appointment of inspectors");
addSection("156", "Appointment of inspectors", 110);
addSection("157", "Identification of inspectors", 110);
addSection("158", "Accountability of inspectors", 110);
addSection("159", "Suspension and ending of appointment of inspectors", 111);
addHeader("Division 2", "Functions and powers of inspectors");
addSection("160", "Functions and powers of inspectors", 111);
addSection("161", "Conditions on inspectors' compliance powers", 112);
addSection("162", "Inspectors subject to regulator's directions", 112);
addHeader("Division 3", "Powers relating to entry");
addHeader("Subdivision 1", "General powers of entry");
addSection("163", "Powers of entry", 112);
addSection("164", "Notification of entry", 112);
addSection("165", "General powers on entry under section 163", 113);
addSection("166", "Persons assisting inspectors", 114);
addHeader("Subdivision 2", "Entry warrants");
addSection("166A", "Terms used", 115);
addSection("166B", "Entry to places under entry warrant", 115);
addSection("167", "Applying for and issuing entry warrant", 115);
addSection("167A", "Use of remote communication", 116);
addSection("167B", "Effect and execution of entry warrant", 118);
addSection("167C", "General powers when executing entry warrant", 119);
addSection("167D", "Persons assisting inspectors", 121);
addSection("168", "Not used", 121);
addSection("169", "Not used", 121);
addHeader("Subdivision 3", "Limitation on entry powers");
addSection("170", "Places used for residential purposes", 121);
addHeader("Division 4", "Powers relating to documents and information");
addSection("171", "Power to require documents and answers to questions", 122);
addSection("172", "Abrogation of privilege against self-incrimination", 124);
addSection("173", "Warning to be given", 125);
addSection("174", "Powers to copy and retain documents", 125);
addHeader("Division 5", "Seizure");
addSection("175", "Power to seize things", 126);
addSection("176", "Inspector's power to seize dangerous workplaces and things", 127);
addSection("177", "Powers supporting seizure", 128);
addSection("178", "Receipt for seized things", 129);
addSection("178A", "Inspecting, examining, analysing and testing seized things", 129);
addSection("179", "Forfeiture of seized things", 130);
addSection("180", "Return of seized things", 131);
addSection("181", "Access to seized things", 132);
addHeader("Division 6", "Damage");
addSection("182", "Damage etc. to be minimised", 132);
addSection("183", "Inspector to give notice of damage", 132);
addSection("184", "Not used", 133);
addHeader("Division 7", "Other matters");
addSection("185", "Power to require name and address", 133);
addSection("186", "Inspector may take affidavits", 134);
addSection("187", "Not used", 134);
addHeader("Division 8", "Offences in relation to inspectors");
addSection("188", "Offence to hinder or obstruct inspector", 134);
addSection("189", "Offence to impersonate inspector", 134);
addSection("190", "Offence to assault, threaten or intimidate inspector", 135);

// Part 10 - Enforcement measures
addHeader("Part 10", "Enforcement measures");
addHeader("Division 1", "Improvement notices");
addSection("191", "Issue of improvement notices", 136);
addSection("192", "Contents of improvement notice", 136);
addSection("193", "Compliance with improvement notice", 137);
addSection("194", "Extension of time for compliance with improvement notices", 137);
addHeader("Division 2", "Prohibition notices");
addSection("195", "Power to issue prohibition notice", 138);
addSection("196", "Contents of prohibition notice", 139);
addSection("197", "Compliance with prohibition notice", 139);
addHeader("Division 3", "Non-disturbance notices");
addSection("198", "Issue of non-disturbance notice", 140);
addSection("199", "Contents of non-disturbance notice", 140);
addSection("200", "Compliance with non-disturbance notice", 141);
addSection("201", "Issue of subsequent notices", 141);
addHeader("Division 4", "General requirements applying to notices");
addSection("202", "Application of Division", 141);
addSection("203", "Notice to be in writing", 141);
addSection("204", "Directions in notices", 141);
addSection("205", "Recommendations in notice", 142);
addSection("206", "Changes to notice by inspector", 142);
addSection("207", "Regulator may vary or cancel notice", 142);
addSection("208", "Formal irregularities or defects in notice", 142);
addSection("209", "Issue and giving of notice", 143);
addSection("210", "Display of notice", 143);
addHeader("Division 5", "Remedial action");
addSection("211", "When regulator may carry out action", 144);
addSection("212", "Power of regulator to take other remedial action", 144);
addSection("213", "Costs of remedial or other action", 145);
addHeader("Division 6", "Not used");
addSection("214", "Not used", 145);
addSection("215", "Not used", 145);

// Part 11 - Enforceable undertakings
addHeader("Part 11", "Enforceable undertakings");
addSection("216", "Regulator may accept WHS undertakings", 146);
addSection("217", "Notice of decision and reasons for decision", 146);
addSection("218", "When a WHS undertaking is enforceable", 146);
addSection("219", "Compliance with WHS undertaking", 147);
addSection("220", "Contravention of WHS undertaking", 147);
addSection("221", "Withdrawal or variation of WHS undertaking", 148);
addSection("222", "Proceeding for alleged contravention", 148);

// Part 12 - Review of decisions
addHeader("Part 12", "Review of decisions");
addHeader("Division 1", "Reviewable decisions");
addSection("223", "Which decisions are reviewable", 149);
addSection("223A", "Review applications by unions", 157);
addHeader("Division 2", "Internal review");
addSection("224", "Application for internal review", 158);
addSection("225", "Internal reviewer", 158);
addSection("226", "Decision of internal reviewer", 158);
addSection("227", "Decision on internal review", 159);
addSection("228", "Stays of reviewable decisions on internal reviews", 159);
addHeader("Division 3", "External review");
addSection("229", "Application for external review", 160);
addSection("229A", "Conduct and outcome of external review", 161);
addSection("229B", "Stays of decisions subject to external review", 162);

// Part 13 - Legal proceedings
addHeader("Part 13", "Legal proceedings");
addHeader("Division 1", "General matters");
addSection("229C", "Terms used", 163);
addSection("230", "Prosecutions", 163);
addSection("231", "Procedure if prosecution is not brought", 164);
addSection("232", "Limitation period for prosecutions", 164);
addSection("232A", "Admission of evidence obtained unlawfully", 166);
addSection("233", "Not used", 167);
addHeader("Division 2", "Sentencing of offenders");
addSection("234", "Application of this Division", 167);
addSection("235", "Orders generally", 167);
addSection("236", "Adverse publicity orders", 167);
addSection("237", "Orders for restoration", 168);
addSection("238", "Work health and safety project orders", 169);
addSection("239", "Release on the giving of a court-ordered WHS undertaking", 169);
addSection("240", "Not used", 170);
addSection("241", "Training orders", 170);
addSection("242", "Offence to fail to comply with order", 170);
addHeader("Division 3", "Not used");
addSection("243", "Not used", 170);
addHeader("Division 4", "Offences by bodies corporate");
addSection("244", "Imputing conduct to bodies corporate", 171);
addHeader("Division 5", "The Crown");
addHeader("Subdivision 1", "Prosecutions");
addSection("244A", "Crown may be prosecuted", 171);
addSection("244B", "Prosecution against agent of Crown that is body corporate", 171);
addSection("244C", "Prosecution of Crown in other cases", 172);
addSection("244D", "Provisions applicable to responsible agency", 172);
addSection("244E", "Proceedings where Crown agency has ceased to exist", 173);
addSection("244F", "Penalties in proceedings against Crown", 174);
addHeader("Subdivision 2", "Other matters");
addSection("244G", "Issue of notices to Crown", 174);
addSection("244H", "Imputing conduct to Crown agency", 175);
addSection("245", "Not used", 176);
addSection("246", "Not used", 176);
addSection("247", "Not used", 176);
addSection("248", "Not used", 176);
addHeader("Division 6", "Not used");
addSection("249", "Not used", 176);
addSection("250", "Not used", 176);
addSection("251", "Not used", 176);
addSection("252", "Not used", 176);
addSection("253", "Not used", 176);
addHeader("Division 7", "Not used");
addSection("254", "Not used", 176);
addSection("255", "Not used", 176);
addSection("256", "Not used", 176);
addSection("257", "Not used", 176);
addSection("258", "Not used", 176);
addSection("259", "Not used", 177);
addSection("260", "Not used", 177);
addSection("261", "Not used", 177);
addSection("262", "Not used", 177);
addSection("263", "Not used", 177);
addSection("264", "Not used", 177);
addSection("265", "Not used", 177);
addSection("266", "Not used", 177);
addHeader("Division 8", "Civil liability not affected by this Act");
addSection("267", "Civil liability not affected by this Act", 177);

// Part 14 - General
addHeader("Part 14", "General");
addHeader("Division 1", "General provisions");
addSection("268", "Offence to give false or misleading information", 178);
addSection("269", "Act does not affect legal professional privilege", 179);
addSection("270", "Immunity from liability", 179);
addSection("271", "Confidentiality of information", 179);
addSection("272", "No contracting out", 181);
addSection("272A", "No insurance or other indemnities against fines", 181);
addSection("273", "Person not to levy workers", 182);
addHeader("Division 2", "Codes of practice");
addSection("274", "Approved codes of practice", 182);
addSection("275", "Use of codes of practice in proceedings", 184);
addHeader("Division 3", "Regulation-making powers");
addSection("276", "Regulation-making powers", 184);
addHeader("Division 4", "Review of Act");
addSection("277", "Operation of Act to be reviewed every 5 years", 186);

// Part 15 - Repeals and consequential amendments
addHeader("Part 15", "Repeals and consequential amendments");
addHeader("Division 1", "Occupational safety and health legislation");
addSection("278", "Occupational Safety and Health Act 1984 repealed", 187);
addSection("279", "Occupational Safety and Health Regulations 1996 repealed", 187);
addHeader("Division 2", "Mines safety and inspection legislation");
addHeader("Subdivision 1", "Mines Safety and Inspection Act 1994 amended");
addSection("280", "Act amended", 187);
addSection("281", "Section 3 deleted", 187);
addSection("282", "Section 4 amended", 187);
addSection("283", "Section 4A deleted", 190);
addSection("284", "Section 6A deleted", 191);
addSection("285", "Section 7 amended", 191);
addSection("286", "Parts 2 to 8 deleted", 191);
addSection("287", "Sections 94 and 95 deleted", 191);
addSection("288", "Section 96A deleted", 191);
addSection("289", "Sections 98 to 99A deleted", 191);
addSection("290", "Section 100 amended", 191);
addSection("291", "Sections 100A and 101 deleted", 191);
addSection("292", "Part 9 Divisions 2 and 3 deleted", 192);
addSection("293", "Sections 102A and 103 deleted", 192);
addSection("294", "Section 104 amended", 192);
addSection("295", "Section 105A amended", 193);
addSection("296", "Section 105AB amended", 193);
addSection("297", "Sections 105 to 110 deleted", 193);
addHeader("Subdivision 2", "Mines Safety and Inspection Regulations 1995 repealed");
addSection("298", "Mines Safety and Inspection Regulations 1995 repealed", 194);
addHeader("Division 3", "Petroleum and geothermal energy legislation");
addHeader("Subdivision 1", "Petroleum and Geothermal Energy Resources Act 1967 amended");
addSection("299", "Act amended", 194);
addSection("300", "Section 5 amended", 194);
addSection("301", "Section 7AA deleted", 194);
addSection("302", "Section 112A amended", 194);
addSection("303", "Section 119 amended", 195);
addSection("304", "Section 126A amended", 195);
addSection("305", "Part IIIA deleted", 195);
addSection("306", "Section 153 amended", 195);
addSection("307", "Schedule 1 deleted", 195);
addHeader("Subdivision 2", "Petroleum and Geothermal Energy Safety Levies Act 2011 amended");
addSection("308", "Act amended", 195);
addSection("309", "Long title amended", 196);
addSection("310", "Section 3 amended", 196);
addSection("311", "Sections 3A to 3E inserted", 200);
addSection("312", "Part 2 replaced", 206);
addHeader("Subdivision 3", "Petroleum Pipelines Act 1969 amended");
addSection("324", "Act amended", 211);
addSection("325", "Section 4 amended", 211);
addSection("326", "Section 5AA deleted", 211);
addSection("327", "Section 32 replaced", 211);
addSection("328", "Section 36 amended", 212);
addSection("329", "Part IVA deleted", 212);
addSection("330", "Section 63 amended", 212);
addSection("331", "Section 66BB amended", 212);
addSection("332", "Section 67 amended", 212);
addSection("333", "Schedule 1 deleted", 212);
addHeader("Subdivision 4", "Petroleum (Submerged Lands) Act 1982 amended");
addSection("334", "Act amended", 213);
addSection("335", "Section 4 amended", 213);
addSection("336", "Section 4A inserted", 213);
addSection("337", "Part IIA deleted", 216);
addSection("338", "Section 97 amended", 216);
addSection("339", "Section 119 amended", 216);
addSection("340", "Section 137A amended", 217);
addSection("341", "Part IIIA deleted", 217);
addSection("342", "Section 152 amended", 217);
addSection("343", "Schedule 3 amended", 217);
addSection("344", "Schedule 5 deleted", 217);
addHeader("Subdivision 5", "Various regulations repealed");
addSection("345", "Regulations under Petroleum and Geothermal Energy Resources Act 1967 repealed", 217);
addSection("346", "Regulations under Petroleum and Geothermal Energy Safety Levies Act 2011 repealed", 218);
addSection("347", "Regulations under Petroleum Pipelines Act 1969 repealed", 218);
addSection("348", "Regulations under Petroleum (Submerged Lands) Act 1982 repealed", 218);
addHeader("Division 4", "Other consequential amendments");
addHeader("Subdivision 1", "Building and Construction Industry Training Fund and Levy Collection Act 1990 amended");
addSection("349", "Act amended", 218);
addSection("350", "Section 8 amended", 219);
addHeader("Subdivision 2", "Constitution Acts Amendment Act 1899 amended");
addSection("351", "Act amended", 219);
addSection("352", "Schedule V amended", 219);
addHeader("Subdivision 3", "Fair Trading Act 2010 amended");
addSection("353", "Act amended", 219);
addSection("354", "Schedule 1 amended", 219);
addHeader("Subdivision 4", "Health (Miscellaneous Provisions) Act 1911 amended");
addSection("355", "Act amended", 220);
addSection("356", "Section 246B amended", 220);
addHeader("Subdivision 5", "Industrial Relations Act 1979 amended");
addSection("357", "Act amended", 220);
addSection("358", "Section 7 amended", 220);
addSection("359", "Section 8 amended", 221);
addSection("360", "Section 16 amended", 221);
addSection("361", "Section 49I amended", 222);
addSection("362", "Section 113 amended", 222);
addHeader("Subdivision 6", "Local Government Act 1995 amended");
addSection("363", "Act amended", 222);
addSection("364", "Section 5.40 amended", 222);
addHeader("Subdivision 7", "Public Sector Management Act 1994 amended");
addSection("365", "Act amended", 223);
addSection("366", "Section 8 amended", 223);
addSection("367", "Section 29 amended", 223);
addHeader("Subdivision 8", "Workers' Compensation and Injury Management Act 1981 amended");
addSection("368", "Act amended", 223);
addSection("369", "Section 47 deleted", 223);
addSection("370", "Section 48 amended", 224);
addSection("371", "Section 95 amended", 224);
addSection("372", "Section 100B amended", 224);

// Part 16 - Transitional provisions
addHeader("Part 16", "Transitional provisions");
addHeader("Division 1", "Preliminary");
addSection("373", "Terms used", 225);
addSection("374", "Application of Interpretation Act 1984 not affected", 225);
addSection("375", "Continued application of enactments", 225);
addSection("376", "Transitional regulations", 226);
addHeader("Division 2", "General saving in relation to certain matters");
addSection("377", "Enactments to continue to apply in relation to certain matters occurring before commencement day", 228);
addHeader("Division 3", "Office holders and bodies");
addSection("378", "WorkSafe Commissioner", 229);
addSection("379", "Chief Inspector of Mines", 229);
addSection("380", "Members of Work Health and Safety Commission", 230);
addSection("381", "First annual report of Work Health and Safety Commission", 231);
addSection("382", "Continuation of Mining Industry Advisory Committee", 231);
addSection("383", "Continuation of other advisory committees", 232);
addHeader("Division 4", "Health and safety duties");
addHeader("Subdivision 1", "Designers");
addSection("384", "Section 22 applies only if designing starts on or after commencement day", 232);
addSection("385", "Continued application of repealed enactments relating to designers", 232);
addHeader("Subdivision 2", "Manufacturers");
addSection("386", "Plant, substance or structure manufactured in batch", 233);
addSection("387", "Section 23 applies only if manufacturing starts on or after commencement day", 233);
addSection("388", "Continued application of repealed enactments relating to manufacturers", 234);
addHeader("Subdivision 3", "Importers");
addSection("389", "Section 24 not to apply if importation process starts before commencement day", 235);
addSection("390", "Continued application of repealed enactments relating to importers", 235);
addHeader("Subdivision 4", "Suppliers");
addSection("391", "Start of supply", 237);
addSection("392", "Section 25 not to apply if supply started before commencement day", 237);
addSection("393", "Continued application of repealed enactments relating to suppliers", 237);
addHeader("Subdivision 5", "Persons who install, construct or commission plant or structures");
addSection("394", "Section 26 not to apply if installing, constructing or commissioning occurs before commencement day", 238);
addSection("395", "Continued application of repealed enactments relating to persons who install or construct plant or structures", 239);
addHeader("Division 5", "Health and safety representatives");
addHeader("Subdivision 1", "Preliminary");
addSection("396", "Terms used", 240);
addHeader("Subdivision 2", "Main provisions");
addSection("397", "Safety and health representatives elected before commencement day", 240);
addSection("398", "Elections in process before commencement day", 242);
addSection("399", "Disqualifications", 243);
addSection("400", "Functions and powers under repealed enactments", 243);
addHeader("Division 6", "Health and safety committees");
addHeader("Subdivision 1", "Preliminary");
addSection("401", "Term used", 244);
addHeader("Subdivision 2", "Main provisions");
addSection("402", "Safety and health committees in place before commencement day", 244);
addSection("403", "Process to establish safety and health committee started before commencement day", 245);
addHeader("Division 7", "Issue resolution");
addSection("404", "Part 5 Division 5 to apply to unresolved issues arising before commencement day", 245);
addSection("405", "Continued application of enactments relating to issue resolution", 246);
addHeader("Division 8", "The regulator");
addSection("406", "Continuing powers and functions under OSHA", 246);
addSection("407", "Continuing powers and functions under MSIA", 246);
addSection("408", "Continuing powers and functions under petroleum and geothermal energy legislation", 247);
addSection("409", "Delegation", 247);
addHeader("Division 9", "Inspectors");
addSection("410", "Inspectors under OSHA", 248);
addSection("411", "Inspectors under MSIA", 249);
addSection("412", "Inspectors under PGERA", 249);
addSection("413", "Inspectors under PPA", 251);
addSection("414", "Inspectors under P(SL)A", 252);
addSection("415", "Application of sections 161 and 162", 253);
addHeader("Division 10", "Legal proceedings");
addSection("416", "Jurisdiction of Occupational Safety and Health Tribunal to be exercised by Tribunal", 253);
addSection("417", "Jurisdiction of safety and health magistrates to be exercised by health and safety magistrates", 254);
addHeader("Division 11", "Other matters");
addSection("418", "Notifiable incidents", 255);
addSection("419", "Independent studies at mines", 255);
addSection("420", "Codes of practice", 255);
addSection("421", "Protections from personal liability", 255);
addHeader("Division 12", "Levies");
addHeader("Subdivision 1", "Mines safety and inspection levy");
addSection("422", "Administration costs", 256);
addSection("423", "Mines Safety and Inspection Levy Regulations 2010", 256);
addHeader("Subdivision 2", "Petroleum and geothermal energy safety levies");
addSection("424", "Administration costs", 257);
addSection("425", "Petroleum and Geothermal Energy Safety Levies Act 2011 to continue to apply to past levy periods", 257);

// Schedule 1 - Various offices and bodies
addHeader("Schedule 1", "Various offices and bodies");
addHeader("Division 1", "WorkSafe Commissioner");
addSection("1", "Appointment of WorkSafe Commissioner", 258);
addSection("2", "Functions of WorkSafe Commissioner and relationship with Minister and WHS department", 258);
addSection("3", "Vacation of office of WorkSafe Commissioner", 259);
addSection("4", "Acting WorkSafe Commissioner", 260);
addHeader("Division 2", "Chief Inspector of Mines and Chief Inspector Petroleum Safety");
addSection("5", "Appointment of Chief Inspector of Mines and Chief Inspector Petroleum Safety", 260);
addSection("6", "Functions of Chief Inspector of Mines and Chief Inspector Petroleum Safety", 261);
addSection("7", "Vacation of office of Chief Inspector of Mines or Chief Inspector Petroleum Safety", 261);
addSection("8", "Acting Chief Inspector of Mines or Acting Chief Inspector Petroleum Safety", 262);
addHeader("Division 3", "Work Health and Safety Commission");
addHeader("Subdivision 1", "Preliminary");
addSection("9", "Terms used", 262);
addHeader("Subdivision 2", "Main provisions");
addSection("10", "Establishment of Work Health and Safety Commission", 263);
addSection("11", "Deputy chairperson", 264);
addSection("12", "Vacation of office of appointed members", 265);
addSection("13", "Acting members", 265);
addSection("14", "Terms and conditions of appointed members", 266);
addSection("15", "Leave of absence", 266);
addSection("16", "Casual vacancies", 267);
addSection("17", "Meetings of Commission", 267);
addSection("18", "Functions of Commission", 268);
addSection("19", "Advisory committees", 270);
addSection("20", "Annual report", 270);
addSection("21", "Staff to assist Commission", 271);
addHeader("Division 4", "Mining and Petroleum Advisory Committee");
addHeader("Subdivision 1", "Preliminary");
addSection("22", "Terms used", 271);
addHeader("Subdivision 2", "Main provisions");
addSection("23", "Establishment of Mining and Petroleum Advisory Committee", 271);
addSection("24", "Functions of Committee", 272);
addSection("25", "Annual report and staff", 272);
addHeader("Division 5", "Work Health and Safety Tribunal");
addHeader("Subdivision 1", "Preliminary");
addSection("26", "Terms used", 273);
addHeader("Subdivision 2", "Main provisions");
addSection("27", "Establishment of Work Health and Safety Tribunal", 273);
addSection("28", "Jurisdiction to be exercised by commissioner with requisite qualifications", 273);
addSection("29", "Practice, procedure and appeals", 274);
addSection("30", "Conciliation", 275);
addSection("31", "Certain matters to be heard together", 276);

// Schedule 2 - Regulation-making powers
addHeader("Schedule 2", "Regulation-making powers");
addSection("1", "Duties", 278);
addSection("2", "Incidents", 278);
addSection("3", "Plant, substances or structures", 278);
addSection("4", "Protection and welfare of workers", 279);
addSection("5", "Hazards and risks", 279);
addSection("6", "Records and notices", 279);
addSection("7", "Authorisations", 280);
addSection("8", "Work groups", 280);
addSection("9", "Health and safety committees and health and safety representatives", 280);
addSection("10", "Issue resolution", 281);
addSection("11", "Identification of inspectors", 281);
addSection("12", "Forfeiture", 281);
addSection("13", "Review of decisions", 281);

console.log(JSON.stringify(sections, null, 2));
